.TH "DALIAS" "1" "0.1.2" "April 2021" "General Commands"
.SH "NAME"
\fBdalias\fR \- Dynamic aliases
.SH "SYNOPSIS"
\fBdalias\fR do <\fIname\fR> <\fIcommand\fR> [\fIarguments\fR]
.br
\fBdalias\fR ed <\fIname\fR>
.br
\fBdalias\fR mv <\fIname\fR> <\fInew_name\fR>
.br
\fBdalias\fR rm <\fIname\fR>
.br
\fBdalias\fR dp <\fIfile\fR>
.br
\fBdalias\fR ls [\fIname\fR|\fIglob\fR]
.br
\fBdalias\fR help
.br
\fBdalias\fR version
.SH "DESCRIPTION"
\fBdalias\fR provides a quick way to create aliases on the go without having to source any script\.
.SH "OPTIONS"
Invoked without options, \fBdalias\fR reads from standard input\.
.P
Available options are:
.P
    - do: create or replace\.
.br
    - ed: edit(1)\.
.br
    - mv: rename\.
.br
    - rm: delete\.
.br
    - dp: dump existing aliases into a file\.
.br
    - ls: print/search dynamic alias list\.
.br
    - help: show help and exit\.
.br
    - version: show program version and exit\.
.P
(1) Make sure \fB$EDITOR\fR environment variable is set.
.SH "BATCH ALIASING"
.P
Since \fBdalias\fR reads from stdin, it is possible to create a bunch of aliases from a file\.
.br
(See \fBSAVE DYNAMIC ALIASES INTO A FILE\fR below\.)
.P
The syntax is as follow:
.IP "" 4
.nf
\fBdalias\fR < file
.fi
.IP "" 0
.P
or
.IP "" 4
.nf
cat file | \fBdalias\fR
.fi
.IP "" 0
.P
Each line of the file must contain \fBdalias\fR \fIdo\fR or \fIrm\fR commands:
.P
<\fIdalias_command\fR> <\fIalias_name\fR> [<\fIcommand\fR> [\fIarguments\fR]]
.P
For now, only \fBdo\fR and \fBrm\fR are available\.
.P
While processing, \fBdalias\fR skips if an error is encountered and indicates on which line the error occured\.
.SH "SAVE DYNAMIC ALIASES INTO A FILE"
.br
You may want to save your aliases, for instance, to use them on another computer\.
.br
To do so:
.IP "" 4
.nf
\fBdalias\fR dp <\fIfile\fR>
.fi
.IP "" 0
.SH "DIRECTORIES"
Dynamic aliases are stored in \fB$HOME/\.config/dalias/aliases\fR directories\. And they are symlinked to
.br
\fB$HOME/\.local/bin\fR\.
.SH "EXAMPLES"
.P
To create a dynamic alias called "da" for \fBdalias\fR:
.IP "" 4
.nf
\fBdalias\fR do da dalias \'"$@"\'
.fi
.IP "" 0
.br
Unlike regular aliases, \fB\'"$@"\'\fR is mandatory since we want be able to pass options to \fBdalias\fR\.
.br
Also notice the surrounding single quotes. They are needed to prevent the shell from interpreting \fB"$@"\fR\.
.P
Another example for \fBls\fR command:
.IP "" 4
.nf
\fBdalias\fR do ll ls \-ahl \-\-group\-directories\-first \-\-color=auto \'"$@"\'
.fi
.IP "" 0
.P
If an alias is made of several commands, semicolons have to be escaped such as in:
.IP "" 4
.nf
\fBdalias\fR do jj clear\\; journalctl -f
.fi
.IP "" 0
.P
A more advanced last example:
.IP "" 4
.nf
\fBdalias\fR do dprm while read -r\\; do echo '"rm $REPLY"' \\| cut -d '=' -f 1\\; done \\< \\<\\(dalias ls\\) \\> rm_aliases
.fi
.IP "" 0
.P
This prints a \fIrm\fR command for every dynamic alias and saves them in a file called "rm_aliases"\.
.br
This syntax is also valid:
.IP "" 4
.nf
\fBdalias\fR do dprm while 'read -r; do echo "rm $REPLY" | cut -d "=" -f 1; done < <(dalias ls) > rm_aliases'
.fi
.IP "" 0
.P
.SH "AUTHOR"
Written by Stéphane MEYER (Teegre)
.SH "REPORTING BUGS"
<\fIhttps://gitlab\.com/teegre/dalias/issues\fR>
.SH "LICENSE"
License GPL\-v3
.P
This is free software provided AS IS with NO WARRANTY\.
.br
Feel free to modify and redistribute\.
.br
For more info, see \fB/usr/share/licenses/dalias/LICENSE\fR
